version: '3.8'
services:
  app:
    image: 127.0.0.1:5000/lab
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    depends_on:
      - mongodb
    networks:
      - node-network
  mongodb:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - node-network

volumes:
  mongodb_data_container:

networks:
  node-network:
    driver: overlay

